Artist.create(name: "The Stooges")
Artist.create(name: "Andrew Hill")
Artist.create(name: "John Coltrane")
Artist.create(name: "Gang Starr")
Artist.create(name: "The Notorious B.I.G.")
Artist.create(name: "Lord Finesse")
Artist.create(name: "Wolf Eyes")
Artist.create(name: "Double Leopards")
Artist.create(name: "Metalux")
Artist.create(name: "Wire")
Artist.create(name: "Discharge")
Artist.create(name: "SPK")
Artist.create(name: "Throbbing Gristle")
Artist.create(name: "Hunting Lodge")
Artist.create(name: "Coil")
Artist.create(name: "Crass")
Artist.create(name: "Wu-Tang Clan")
Artist.create(name: "Bolt Thrower")
Artist.create(name: "Black Sabbath")
Artist.create(name: "Napalm Death")
Artist.create(name: "Sleep")
Artist.create(name: "Albert Ayler")
Artist.create(name: "Sonny Sharrock")
Artist.create(name: "Al Green")
Artist.create(name: "Betty Davis")
Artist.create(name: "Marva Whitney")
Artist.create(name: "Cymande")



Album.create(title: "Raw Power", format: "CD", year: 1973, artist_id: 1)
Album.create(title: "Fun House", format: "CD", year: 1970, artist_id: 1)
Album.create(title: "Point Of Departure", format: "CD", year: 1965, artist_id: 2)
Album.create(title: "A Love Supreme", format: "CD", year: 1965, artist_id: 3)
Album.create(title: "A Hole Is True", format: "CD", year: 2005, artist_id: 8)




Genre.create(name: "Punk")
Genre.create(name: "Hip-Hop")
Genre.create(name: "Noise")
Genre.create(name: "Industrial")
Genre.create(name: "Metal")
Genre.create(name: "Soul")
Genre.create(name: "Jazz")

ArtistAlbumSongGenres.create(artist_id: 1, album_id: 1, genre_id: 1)
ArtistAlbumSongGenres.create(artist_id: 1, album_id: 2, genre_id: 1)
ArtistAlbumSongGenres.create(artist_id: 2, album_id: 3, genre_id: 7)
ArtistAlbumSongGenres.create(artist_id: 3, album_id: 4, genre_id: 7)
ArtistAlbumSongGenres.create(artist_id: 4, album_id: 5, genre_id: 3)